
[project]
name = "pdm-template-rudeigerc"
version = "0.1.0"
description = ""
authors = [
    {name = "rudeigerc", email = "rudeigerc@gmail.com"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
