
[project]
name = "pdm-template-rudeigerc"
version = "0.1.0"
description = ""
authors = [
    {name = "rudeigerc", email = "rudeigerc@gmail.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
lint = [
    "ruff>=0.0.287",
    "black>=23.9.0",
    "mypy>=1.5.1",
    "pre-commit>=3.4.0",
]
docs = [
    "mkdocs>=1.5.2",
    "mkdocs-material>=9.2.8",
    "mkdocstrings>=0.23.0",
    "mkdocstrings-python>=1.6.2",
]
test = [
    "pytest>=7.4.2",
    "pytest-cov>=4.1.0",
]

[tool.pdm.scripts]
lint = "pre-commit run --all-files"
docs = "mkdocs serve"
test = "pytest -v tests"

[[tool.pdm.source]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
name = "tuna"

[[tool.pdm.source]]
url = "https://mirror.sjtu.edu.cn/pypi/web/simple"
name = "sjtug"

[tool.ruff]
line-length = 88
select = [
    # flake8-bugbear
    "B",
    # pycodestyle - Error
    "E",
    # Pyflakes
    "F",
    # isort
    "I",
    # pycodestyle - Warning
    "W"
]
exclude = ["E501"]

[tool.ruff.pydocstyle]
convention = "google"
